/**
 * Regional harvest calendars for HarvestMap.
 *
 * Loads the committed data file (src/data/regional-harvest-calendars.json),
 * generated by scripts/refresh-harvest-calendars.ts from PickYourOwn.org
 * state harvest calendars plus the fall windows vetted in HarvestMap's outing
 * guides. This is the "real 'what's ripe now'" layer: month windows per crop,
 * per region, that the outing and crop pages render.
 *
 * Unlike src/lib/seasonality.ts (a per-farm latitude→zone estimate), this data
 * is region-specific and elevation-aware where the guides documented it.
 */

import calendarsData from '../data/regional-harvest-calendars.json';

export interface RegionCrop {
  crop: string;
  slug: string;
  start: number; // 1-12
  end: number; // 1-12 (wraps when end < start, e.g. citrus)
  peak?: number[];
  months: string;
  fall?: boolean;
  note?: string;
}

export interface RegionalCalendar {
  id: string;
  name: string;
  state: string;
  bestWindow?: string;
  crops: RegionCrop[];
}

interface CalendarsData {
  generatedAt: string;
  source: string;
  regions: RegionalCalendar[];
}

const data = calendarsData as CalendarsData;

export function getRegionCalendars(): RegionalCalendar[] {
  return data.regions;
}

export function getRegionCalendar(id: string): RegionalCalendar | undefined {
  return data.regions.find((r) => r.id === id);
}

/** Match a guide `region` string ("Hudson Valley, NY") to a calendar id. */
export function findCalendarByRegionName(region: string): RegionalCalendar | undefined {
  const needle = region.toLowerCase().split(',')[0].trim();
  return data.regions.find((r) => {
    const id = r.id.replace(/-/g, ' ');
    const name = r.name.toLowerCase();
    return name === needle || name.includes(needle) || needle.includes(name) || id === needle;
  });
}

export function isMonthInWindow(month: number, start: number, end: number): boolean {
  if (start <= end) return month >= start && month <= end;
  return month >= start || month <= end; // wraps year-end (e.g. citrus)
}

/** Crops in season in a given region for a given month (1-12). */
export function cropsInSeason(calendar: RegionalCalendar, month: number): RegionCrop[] {
  return calendar.crops.filter((c) => isMonthInWindow(month, c.start, c.end));
}

/** Fall-harvest crops for a region, in calendar order. */
export function fallCrops(calendar: RegionalCalendar): RegionCrop[] {
  return calendar.crops.filter((c) => c.fall);
}

export function getRegionCrop(calendar: RegionalCalendar, slug: string): RegionCrop | undefined {
  return calendar.crops.find((c) => c.slug === slug);
}

/** Which of the five regions have this crop in season in a given month. */
export function regionsWithCropInSeason(
  slug: string,
  month: number,
): { region: RegionalCalendar; crop: RegionCrop }[] {
  return data.regions
    .map((region) => {
      const crop = getRegionCrop(region, slug);
      if (!crop) return null;
      return isMonthInWindow(month, crop.start, crop.end) ? { region, crop } : null;
    })
    .filter((x): x is { region: RegionalCalendar; crop: RegionCrop } => x !== null);
}

export const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];
