import type { APIRoute } from 'astro';

// /sitemap.xml is the URL crawlers and tools try by default. The real index
// is /sitemap-index.xml (generated by @astrojs/sitemap), so send them there.
export const prerender = false;

export const GET: APIRoute = ({ site }) =>
  new Response(null, {
    status: 301,
    headers: { Location: new URL('/sitemap-index.xml', site).href },
  });
